name: Lint and Format

on: [pull_request]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort

      - name: Run isort check
        run: isort . --check --diff

      - name: Run black check
        run: black . --check
